### PR TITLE
Thunderbird 102 ESR

### PR DESCRIPTION
**Pull request by HorlogeSkynet**
## Description

* Arkenfox v91.1 -> v102.1 migration for new ESR
* Adds `app.use_without_mail_account` (v93)
* Enforces `mail.compose.warn_public_recipients.*` preferences (v93) 
* Switches to `mail.default_send_format` to send plaintext email (v101)
* Adds `mail.biff.use_new_count_in_badge` to template
* Gets rid of `mail.calendar-integration.opt-out` & `calendar.useragent.extra`
* Cleans outdated `0300` section documentation (related to auto-install)
* Disables new `calendar.extract.service.enabled` preference
* Adds `mail.biff.show_alert` and `mail.biff.alert.show_*` preferences
* Removes unnecessary leading spaces in some documentation lines
* Enforces `mail.compose.add_link_preview`
* Enforces `mailnews.message_display.disable_remote_image`

## How has this been tested ?

* On Windows (Thunderbird v102.2.2)
* On Linux (Thunderbird v102.2.0)

## Types of changes :

- Bug fix (non-breaking change which fixes an issue)
- [X] Typo / style fix (non-breaking change which improves readability)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist :

- [X] My changes looks good ;
- [X] I agree that my code may be modified in the future ;
- [X] My code follows the code style of this project (see `.eslintrc.yml`).

### CODE REVIEW

**Comment by Dupond** [comment]
Hi,

Thank you very much for your work!

I just wanted to mention that in my Thunderbird, the pref "app.use_without_mail_account" set to "true" causes the mail folders and the messages to be hidden. I use Thunderbird 102.2.0 in Arch Linux. It could be a Thunderbird bug, however...

**Comment by HorlogeSkynet** [comment]
> Hi,

Hi @Dupond !

> Thank you very much for your work!

Thank you, very appreciated.

> I just wanted to mention that in my Thunderbird, the pref "app.use_without_mail_account" set to "true" causes the mail folders and the messages to be hidden. I use Thunderbird 102.2.0 in Arch Linux. It could be a Thunderbird bug, however...

Nice feedback, maybe an oversight from me. By looking at the source code again, this came up : https://searchfox.org/comm-esr102/rev/d9800535d0b488462c8ae64f7fe6647cc42535e1/mail/base/content/msgMail3PaneWindow.js#714-722

We might end up leaving this preference commented out in the template, for users **not** using TB for emails, but maybe for calendar, address books or even IM. What do you think about that ?

Bye 👋

PS : BTW, if by chance you are interested, this project definitely need maintainers/reviewers ! 🙂

**Comment by Dupond** [comment]
> We might end up leaving this preference commented out in the template, for users not using TB for emails, but maybe for calendar, address books or even IM. What do you think about that ?

Seems nice!

> PS : BTW, if by chance you are interested, this project definitely need maintainers/reviewers !

I don't have the time (nor the skill), unfortunately; sorry about that... You project is really nice, though; it's really useful; I like all the decisions you made about including some prefs or not. And I can imagine that reviewing the Arkenfox *and* the Thunderbird code regularly must ask a lot of time; I'm really sorry I can't help.

**Comment by HorlogeSkynet** [comment]
> I don't have the time (nor the skill), unfortunately; sorry about that... You project is really nice, though; it's really useful; I like all the decisions you made about including some prefs or not. And I can imagine that reviewing the Arkenfox and the Thunderbird code regularly must ask a lot of time; I'm really sorry I can't help.

Hey @Dupond,

Sorry for the delay.
By maintainer I didn't necessarily mean "developer", but also "reviewer" or "tester" (thus more or less what you've done here, that's why I wanted to propose you).
Indeed, this project is pretty much time consuming, and classically, there are daily new users (and the TB dev team has gone 🚀 lately), but with the same manpower as before.
(my) Pull requests definitely need reviews and tests on _other_ setups.

Feel free not to answer here, I just wanted to clarify what I meant previously 🙏
Bye 👋

**Comment by Dupond** [comment]
Well, I do use your `thunderbird-user.js` file on a daily basis, and I use Arch, which is a rolling release, and thus I will always test the last version of your project. So if it's just that, of course I'm OK to report any problem I may encounter ;)

Have a nice day!

**Review by Dupond — APPROVED** [review]
Sorry for the loooong delay! I've been really busy.

I've applied the last commits, and everything seems fine on my side! Thanx for the good work!

**Pull request merged**
