### PR TITLE
Thunderbird 115 ESR

### PR DESCRIPTION
**Pull request by HorlogeSkynet**
## Description

- [x] Upstream `mailnews.js` comparison (https://searchfox.org/comm-esr102/source/mailnews/mailnews.js & https://searchfox.org/comm-esr115/source/mailnews/mailnews.js)
- [x] Arkenfox v102.1 -> v115 migration for new ESR (https://github.com/arkenfox/user.js/compare/102.1...115.1#diff-417e8f625f16252f8ace3b0791d24c9b073d7394e9216c7b5d14a516d2572277)

## How has this been tested ?

TB v115.3.1 on Linux.

## Types of changes :

- [x] Bug fix (non-breaking change which fixes an issue)
- Typo / style fix (non-breaking change which improves readability)
- [x] New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist :

- [x] My changes looks good ;
- [x] I agree that my code may be modified in the future ;
- [x] My code follows the code style of this project (see `.eslintrc.yml`).

### CODE REVIEW

**Comment by quantumpacket** [comment]
Will this be merged and a new release made since TB 115 has been released for awhile now?

**Comment by HorlogeSkynet** [comment]
Hi, yes this _will_ be merged, someday. The Arkenfox "migration" still requires to be performed, and I am waiting for TB 115 upgrade on at least one of my machines to properly work on it.
Thanks, bye 👋

**Comment by HorlogeSkynet** [comment]
Hi @quantumpacket, branch is ready for review for 115. I kindly ask @Dupond again but _any_ feedback will be appreciated.
Bye :wave:

**Comment by HorlogeSkynet** [comment]
Merge and release scheduled in 7 days (18/11/2023), unless someone gives a negative feedback/review beforehand :pray:

**Pull request merged**
